export const NICK_PROVIDED = 'NICK_PROVIDED'
export const USER_TO_CHAT_SELECTED = 'USER_TO_CHAT_SELECTED'
export const UPDATE_ALL_USERS_ONLINE = 'UPDATE_ALL_USERS_ONLINE'
export const CONNECT_SOCKET = 'CONNECT_SOCKET'