export const PROVIDE_NICK = 'PROVIDE_NICK'
export const USER_TO_CHAT_SELECTED = 'USER_TO_CHAT_SELECTED'
export const UPDATE_ALL_USERS_ONLINE = 'UPDATE_ALL_USERS_ONLINE'
export const JOIN_ROOM = 'JOIN_ROOM'