const ALL_USERS_ONLINE = 'ALL_USERS_ONLINE'
const INVITE_USER_TO_CHAT = 'INVITE_USER_TO_CHAT'
const START_PEER_CONNECTION = 'START_PEER_CONNECTION'

module.exports = {
    ALL_USERS_ONLINE,
    INVITE_USER_TO_CHAT,
    START_PEER_CONNECTION
}